name: Clean Repository History
on:
  workflow_dispatch:
    inputs:
      confirm:
        type: boolean
        description: Confirm to clean the repository history
        required: true
        default: false

jobs:
  clean_history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # 获取完整的提交历史

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython

      

      - name: Run Python script to clean history
        run: |
          python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
          maill: ${{ secrets.maill }}
          namee: ${{ secrets.namee }}
