name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          fetch-depth: 1  # 1最新，0完整
      - name: Replace URLs in JSON file
        run: |
          curl -sS -o a/up.json https://u.david525.cloudns.ch
          curl -sS -o a/upmin.json https://u.david525.cloudns.ch?f=m
          find a  -type f -name "*.json" -exec sed -i 's|https://d.david525.cloudns.ch/ck/|../|g' {} +
          find p pmin -type f -name "jsm.json" -exec sed -i 's|http://d.david525.cloudns.ch/CatVodSpider/jar|../a|g' {} +
          find p pmin -type f -name "jsm.json" -exec sed -i 's|"http://up.david525.cloudns.ch"|"../a/up.json"|g' {} +
          find p pmin -type f -name "jsm.json" -exec sed -i 's|http://r.david525.cloudns.ch|../a|g' {} +
          find p pmin -type f -name "jsm.json" -exec sed -i 's|"http://up.david525.cloudns.ch?filter=min"|"../a/upmin.json"|g' {} +
          #find p pmin -type f -name "*.zip" -exec rm {} +
          #find p -type d -exec zip -r p.zip {} +
          #find pmin -type d -exec zip -r pmin.zip {} +
          
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string        
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_POND_0FBB05C00 }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/" # Built app content directory - optional
          github_id_token: ${{ steps.idtoken.outputs.result }}
          ###### End of Repository/Build Configurations ######
        env:
          SKIP_BUILD : true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
