name: Upload Packages

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Zip and Upload pg.zip
        run: |
          cd $GITHUB_WORKSPACE
          zip -r pg.zip p/
          curl -X PUT --data-binary @pg.zip "https://r.david525.cloudns.ch/pg.zip"

      - name: Zip and Upload zx.zip
        run: |
          cd $GITHUB_WORKSPACE
          zip -r zx.zip z/
          curl -X PUT --data-binary @zx.zip "https://r.david525.cloudns.ch/zx.zip"

      - name: Zip and Upload pgmin.zip
        run: |
          cd $GITHUB_WORKSPACE
          zip -r pgmin.zip pmin/
          curl -X PUT --data-binary @pgmin.zip "https://r.david525.cloudns.ch/pgmin.zip"
